### ISSUE TITLE
seccfg error

### ISSUE THREAD

**Issue by 330wang** [bkerler/mtkclient#40] opened 2021-09-02 08:04 UTC
File "d:\Tools\PortableGit\mtkclient\stage2", line 637, in <module>
    main()
  File "d:\Tools\PortableGit\mtkclient\stage2", line 627, in main
    data = seccfg_data + enc_hash
TypeError: can't concat list to bytes

**Comment by 330wang** [comment] 2021-09-02 08:08
stage2  Line:389 Line:395

 if mode == "sej_aes_decrypt":
            dec_data = self.hwcrypto.aes_hwcrypt(mode="cbc", data=data, btype="sej", encrypt=**False**)
            keyinfo+="\n"
            keyinfo+="Data: " + hexlify(dec_data).decode('utf-8')
            keyinfo+="\n"
            return dec_data, keyinfo
        elif mode == "sej_aes_encrypt":
            enc_data = self.hwcrypto.aes_hwcrypt(mode="cbc", data=data, btype="sej", encrypt=**False**)
            keyinfo+="\n"
            keyinfo+="Data: " + hexlify(enc_data).decode('utf-8')
            keyinfo+="\n"
            return enc_data, keyinfo

**Comment by bkerler** [comment] 2021-09-02 08:48
Duplicate of #33

**Closed by bkerler** 2021-09-02 08:48 UTC
