### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by bukaixyz** [bkerler/mtkclient#247] opened 2022-01-24 05:45 UTC
[log.txt](https://github.com/bkerler/mtkclient/files/7922941/log.txt)

**Comment by bukaixyz** [comment] 2022-01-24 05:46
@bkerler

**Comment by bkerler** [comment] 2022-01-26 20:16
You need to boot into brom, not preloader mode. Closing this issue as no further description was provided what the issue is other than sla error

**Closed by bkerler** 2022-01-26 20:16 UTC
