### ISSUE TITLE
Stage was't executed. Maybe dram issue ?. 

### ISSUE THREAD

**Issue by Goku9650** [bkerler/mtkclient#1154] opened 2024-08-18 08:58 UTC
I was trying to unlock bootloader of my Oppo A12 and i kept getting this error

Stage was't executed. Maybe dram issue ?.
DAXFlash
DAXFlash - [LIB]: DA Extensions failed to enable

**Comment by bkerler** [comment] 2024-08-24 08:56
Duplicate of #1152

**Closed by bkerler** 2024-08-24 08:56 UTC
