### ISSUE TITLE
Error in arch linux

### ISSUE THREAD

**Issue by atharvnegi** [bkerler/mtkclient#1191] opened 2024-09-06 08:39 UTC
Traceback (most recent call last):
  File "/home/atharv2951/Desktop/mtkclient/mtk.py", line 1016, in <module>
    main()
  File "/home/atharv2951/Desktop/mtkclient/mtk.py", line 1012, in main
    mtk = Main(args).run(parser)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/atharv2951/Desktop/mtkclient/mtkclient/Library/mtk_main.py", line 664, in run
    da_handler.handle_da_cmds(mtk, cmd, self.args)
  File "/home/atharv2951/Desktop/mtkclient/mtkclient/Library/DA/mtk_da_handler.py", line 877, in handle_da_cmds
    v = mtk.daloader.seccfg(args.flag)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/atharv2951/Desktop/mtkclient/mtkclient/Library/DA/mtk_daloader.py", line 392, in seccfg
    return self.xft.seccfg(lockflag)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/atharv2951/Desktop/mtkclient/mtkclient/Library/DA/xflash/extension/xflash.py", line 654, in seccfg
    if self.xflash.writeflash(addr=partition.sector * self.mtk.daloader.daconfig.pagesize,
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/atharv2951/Desktop/mtkclient/mtkclient/Library/DA/xflash/xflash_lib.py", line 938, in writeflash
    if os.path.exists(filename):
       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen genericpath>", line 19, in exists
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

**Comment by fukiame** [comment] 2024-09-06 09:26
duplicate of #1167

**Comment by bkerler** [comment] 2024-09-17 17:17
[8fff2ab](https://github.com/bkerler/mtkclient/commit/8fff2aba850e280e2f22da938b67cbf7da3d2b5c)

**Closed by bkerler** 2024-09-17 17:17 UTC
