### ISSUE TITLE
Fuse library not found even after installing winfsp

### ISSUE THREAD

**Issue by yakupaslantas** [bkerler/mtkclient#1150] opened 2024-08-16 16:00 UTC
I tried older versions of winfsp but it didnt worked

**Comment by yakupaslantas** [comment] 2024-08-17 20:43
I am on windows 10 and python 3.12 all requirements are installed

**Comment by bkerler** [comment] 2024-08-24 09:04
Duplicate of #992

**Closed by bkerler** 2024-08-24 09:04 UTC
